#FROM rust:latest as builder
#
#RUN apt update && apt upgrade -y && rm -rf /var/lib/apt/lists/*
#
#WORKDIR APP
#
#ADD . /APP
#
#WORKDIR /forum-backend
#RUN rm -rf target/*
#RUN cargo build --release

FROM debian:bookworm

CMD ["/bin/bash"]

#COPY --from=builder forum-backend/target/release/forum-backend /usr/src

#WORKDIR /usr/src

#RUN ls
#CMD ./forum-backend